print('CONSOLE RESPONDENDO USUARIO V1')
print('\n')
nome = input('DIGITE SEU NOME: ')
print('\n')
idade = input('DIGITE SUA IDADE: ')
print('\n')
cidade = input('DIGITE A CIDADE EM QUE VOCÊ NASCEU: ')
print('\n')
mae = input('DIGITE O NOME DA SUA MÃE: ')
print('\n')
pai = input('DIGITE O NOME DO SEU PAI: ')
print('\n')
d = input('DIGITE O DIA EM QUE VOCÊ NASCEU:')
print('\n')
m = input('DIGITE O MÊS EM QUE VOCÊ NASCEU: ')
print('\n')
a = input('DIGITE O ANO EM QUE VOCÊ NASCEU: ')
print('\n')

print('SEU NOME É {}, VOCÊ TEM {} ANOS, NASCEU EM {}, O NOME DA SUA MÃE É {}, O NOME DO SEU PAI É {}, E SUA DATA DE NASCIMENTO É {}/{}/{}.'.format(nome,idade,cidade,mae,pai,d,m,a))
print('\n')
f = input('DIGITE QUALQUER COISA PARA FECHAR: ')
print('fechando {}'.format(f))